### ISSUE TITLE
Mission Statement

### ISSUE THREAD

**Issue by aikenorganics** [aikenorganics/aikenorganics.com#10] opened 2015-03-01 19:34 UTC
Can we add this somewhere?

Aiken Organics mission is to connect local farmers to the community, and improve lives through food.   AO will be the most trusted organic and natural online food market and a place where healthy decisions are easy.  AO will educate the community on the importance of local, fresh and organic food.

**Comment by braddunbar** [comment] 2015-05-22 19:24
Duplicate of #14.

**Closed** 2015-05-22 19:24 UTC
Labels: high
